# Setup
title:               Victor Qin
description:         'Built with Jekyll theme <a href="https://lanyon.getpoole.com/" target="_blank">Lanyon</a> and <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a>.'
url:                 https://victor-qin.github.io
baseurl:             ''
paginate:            20
permalink:           pretty


# About/contact
author:
  name:              Victor Qin
  url:               https://victor-qin.github.io
  email:             lingheng.qin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
